### ISSUE TITLE
reordering not working

### ISSUE THREAD

**Issue by ColinMcMicken** [thombashi/tcconfig#101]
CentOS Linux release 7.5.1804 (Core)
Python 2.7.5
tcconfig                     0.20.0

tcset ens33 --add --reordering 99
Traceback (most recent call last):
  File "/usr/bin/tcset", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python2.7/site-packages/tcconfig/tcset.py", line 338, in main
    return_code = tc.set_tc()
  File "/usr/lib/python2.7/site-packages/tcconfig/traffic_control.py", line 282, in set_tc
    return self.__shaper.set_shaping()
  File "/usr/lib/python2.7/site-packages/tcconfig/shaper/htb.py", line 215, in set_shaping
    self._set_netem()
  File "/usr/lib/python2.7/site-packages/tcconfig/shaper/_interface.py", line 123, in _set_netem
    handle=handle,
  File "/usr/lib/python2.7/site-packages/tcconfig/_common.py", line 162, in run_command_helper
    logger.error(error_msg_format.format(command, proc.stderr))
KeyError: u'uniform|normal|pareto|paretonormal'

**Comment by thombashi** [comment]
@ColinMcMicken 
Thank you for your report.
I had fixed the problem at `tcconfig 0.20.1`.
Please upgrade the package and re-execute.

Note: You will also need `--delay` option to use `--reordering` option
e.g. `tcset ens33 --add --reordering 99 --delay 20ms`
