### ISSUE TITLE
Tcset fails to set bandwidth rate of 100 Mbit/s

### ISSUE THREAD

**Issue by ddib-ccde** [thombashi/tcconfig#36]
When trying to set a rate of 100 Mbit/s on an interface, tcset fails with the following message:

`Traceback (most recent call last):
  File "/usr/local/bin/tcset", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/tcconfig/tcset.py", line 218, in main
    tc.set_tc()
  File "/usr/local/lib/python2.7/dist-packages/tcconfig/traffic_control.py", line 102, in set_tc
    self.__set_rate(qdisc_major_id)
  File "/usr/local/lib/python2.7/dist-packages/tcconfig/traffic_control.py", line 400, in __set_rate
    max(rate_kbps, self.__MIN_BUFFER_BYTE)),  # [byte]
ValueError: Unknown format code 'd' for object of type 'float'`

When debug option is used the following commands are output by tcset:

`[2016-11-11 09:47:09.580771] DEBUG: subprocrunner: lsmod | grep sch_netem
[2016-11-11 09:47:09.585109] DEBUG: subprocrunner: tc qdisc add dev ens192.190 root handle 1040: prio
[2016-11-11 09:47:09.587466] DEBUG: subprocrunner: tc filter add dev ens192.190 protocol ip parent 1040: prio 2 u32 match ip dst 0.0.0.0/0 flowid 1040:1
[2016-11-11 09:47:09.589509] DEBUG: subprocrunner: tc qdisc add dev ens192.190 parent 1040:1 handle 104a: netem`

When the command is used successfully such as setting rate to 100 kbit/s the following commands are logged:

`[2016-11-11 09:47:41.265752] DEBUG: subprocrunner: tc qdisc add dev ens192.190 root handle 1040: prio
[2016-11-11 09:47:41.268064] WARNING: subprocrunner: returncode=2, stderr=RTNETLINK answers: File exists
[2016-11-11 09:47:41.268512] DEBUG: subprocrunner: tc filter add dev ens192.190 protocol ip parent 1040: prio 2 u32 match ip dst 0.0.0.0/0 flowid 1040:1
[2016-11-11 09:47:41.270733] DEBUG: subprocrunner: tc qdisc add dev ens192.190 parent 1040:1 handle 104a: netem
[2016-11-11 09:47:41.273082] WARNING: subprocrunner: returncode=2, stderr=RTNETLINK answers: File exists
[2016-11-11 09:47:41.273447] DEBUG: subprocrunner: tc qdisc add dev ens192.190 parent 104a:1 handle 20: tbf rate 100.000000kbit buffer 1600 limit 10000`

Is this a bug in tcset or is it an issue with tc itself?

**Comment by thombashi** [comment]
@ddib-ccde
Thank you for your report.

It would probably a problem of `tcset`.
I've update `tcconfig` to `0.7.0-alpha-1`.
I believe this version fixed the problem.
Could you upgrade `tcconfig` and re-execute the same command?
You could upgrade by `pip install tcconfig --upgrade --pre`

**Comment by ddib-ccde** [comment]
Hi.

Now it works as expected. Thank you!
