### ISSUE TITLE
ImportError: No module named _threading

### ISSUE THREAD

**Issue by xz-zhuqi** [thombashi/tcconfig#74]
tcset --help
Traceback (most recent call last):
  File "/usr/local/bin/tcset", line 9, in <module>
    load_entry_point('tcconfig==0.12.0', 'console_scripts', 'tcset')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 337, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2279, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1989, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/usr/local/lib/python2.7/dist-packages/tcconfig/tcset.py", line 15, in <module>
    import logbook
  File "/usr/local/lib/python2.7/dist-packages/logbook/__init__.py", line 14, in <module>
    from .base import (
  File "/usr/local/lib/python2.7/dist-packages/logbook/base.py", line 19, in <module>
    from logbook.concurrency import (greenlet_get_ident, thread_get_ident,
  File "/usr/local/lib/python2.7/dist-packages/logbook/concurrency.py", line 31, in <module>
    from gevent._threading import (Lock as ThreadLock,
ImportError: No module named _threading

**Comment by thombashi** [comment]
Thank you for your report.

Would you upgrade `gevent` package to greater or equal to `1.0` by `pip install gevent --upgrade`? (latest version would be preferable). You could solve the problem by that.
I assume your environment installed `gevent` that older or equal to `0.13.8`.

I can reproduce the problem:

```
[~]# pip show gevent | \grep Version
Version: 0.13.8
[~]# tcset -h
Traceback (most recent call last):
  File "/usr/local/bin/tcset", line 7, in <module>
    from tcconfig.tcset import main
  File "/usr/local/lib/python2.7/dist-packages/tcconfig/tcset.py", line 15, in <module>
    import logbook
  File "/usr/local/lib/python2.7/dist-packages/logbook/__init__.py", line 14, in <module>
    from .base import (
  File "/usr/local/lib/python2.7/dist-packages/logbook/base.py", line 19, in <module>
    from logbook.concurrency import (greenlet_get_ident, thread_get_ident,
  File "/usr/local/lib/python2.7/dist-packages/logbook/concurrency.py", line 31, in <module>
    from gevent._threading import (Lock as ThreadLock,
ImportError: No module named _threading
[~]#
```

```
[~]# pip show gevent | \grep Version
Version: 1.2.2
[~]# tcset --help
usage: tcset [-h] [--version] [--tc-command | --tc-script] [--debug | --quiet]
             (--device DEVICE | -f CONFIG_FILE)
             [--overwrite | --change | --add]
             [--direction {outgoing,incoming}] [--rate BANDWIDTH_RATE]
             [--delay NETWORK_LATENCY] [--delay-distro LATENCY_DISTRO_MS]
             [--loss PACKET_LOSS_RATE] [--duplicate PACKET_DUPLICATE_RATE]
             [--corrupt CORRUPTION_RATE] [--reordering REORDERING_RATE]
             [--network DST_NETWORK] [--port DST_PORT] [--src-port SRC_PORT]
             [--ipv6] [--shaping-algo {tbf,htb}] [--iptables]
             [--src-network SRC_NETWORK]
...
```

**Comment by xz-zhuqi** [comment]
Thanks for your reply
I have solved the problem according to your solution
